### ISSUE TITLE
Please Consider Semantic Versioning

### ISSUE THREAD

**Issue by zbindenren** [jfrog/jfrog-client-go#34] opened 2019-01-28 11:41 UTC
Please consider [semantic versioning](https://semver.org/).

You tagged a new release 0.2.2 18h ago, but this version is incompatible with 0.2.1. Patch releases should be backwards-compatible bug fixes.

**Comment by RobiNino** [comment] 2019-01-28 12:56
@zbindenren,
You are correct. Following the API changes, this should have been released as a minor release and not a patch. We apologise for the inconvenience caused by this.
We've just updated the README with the API changes and released a new minor version.
Thanks

**Closed** 2019-01-28 14:22 UTC
